name: LEDE Firmware Build

on:
  workflow_dispatch:
    inputs:
      device:
        description: '设备型号'
        required: true
        default: 'r68s'
        type: choice
        options:
        - r68s
        - x86
      kernel:
        description: '内核版本'
        required: true
        default: '6.6'
      ip:
        description: '默认IP地址'
        required: true
        default: '192.168.1.180'
      hostname:
        description: '主机名'
        required: true
        default: 'lede-router'
      build_dir:
        description: '编译目录'
        required: true
        default: '/mnt'
      clean:
        description: '清理编译'
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Build Environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
        genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
        libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
        libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
        python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
        swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
